// Output settings are read here; app.js consumes the resulting settings object.
function getSettings(){
  const textFont = document.getElementById('textFont').value;
  const advancedOn = document.getElementById('advancedOn').checked;
  return {
    imgOn: document.getElementById('imgOn').checked,
    imgUrl: document.getElementById('imgUrl').value.trim(),
    imageLoadFailed: document.getElementById('imageLoadStatus')?.dataset?.state === 'error',
    imgHeight: document.getElementById('imgHeight').value,
    xpos: document.getElementById('xpos').value,
    ypos: document.getElementById('ypos').value,
    narrFont: textFont,
    narrSize: document.getElementById('narrSize').value,
    narrLine: document.getElementById('narrLine').value,
    narrColor: document.getElementById('narrColor').value,
    dlgStyle: document.getElementById('dlgStyle').value,
    dlgFont: textFont,
    dlgSize: document.getElementById('dlgSize').value,
    dlgLine: document.getElementById('dlgLine').value,
    titleSize: document.getElementById('titleSize').value,
    titleBold: document.getElementById('titleBold').checked,
    foldTitleSize: document.getElementById('foldTitleSize').value,
    foldTitleBold: document.getElementById('foldTitleBold').checked,
    foldTitleMinimal: !document.getElementById('foldTitleDecorationOn').checked,
    foldDividerMinimal: !document.getElementById('foldDividerOn').checked,
    foldTitleAutoNumber: document.getElementById('foldTitleAutoNumber').checked,
    charColor: document.getElementById('charColor').value,
    userColor: document.getElementById('userColor').value,
    emphasisColor: document.getElementById('emphasisColor').value,
    parallelTranslationSoft: document.getElementById('parallelTranslationLayout').value !== 'off',
    parallelTranslationLayout: document.getElementById('parallelTranslationLayout').value,
    charSpeakerOn: document.getElementById('charSpeakerOn').checked,
    userSpeakerOn: document.getElementById('userSpeakerOn').checked,
    extraChars: parseExtraChars(),
    charName: document.getElementById('charName').value,
    userName: document.getElementById('userName').value,
    footerOn: document.getElementById('footerOn').checked,
    footerAuthor: document.getElementById('footerAuthor').value,
    creditOn: document.getElementById('creditOn').checked,
    creditPlacement: normalizeCreditPlacement(document.getElementById('creditPlacement').value),
    creditItems: storedCreditItems(),
    logTitleOn: document.getElementById('logTitleOn').checked,
    titleMinimal: document.getElementById('titleMinimal').checked,
    titleImageBackgroundOn: document.getElementById('titleImageBackgroundOn').checked,
    logNumber: document.getElementById('logNumber').value,
    logTitle: document.getElementById('logTitle').value,
    subChar: document.getElementById('subChar').value,
    subUser: document.getElementById('subUser').value,
    subtitleCoupleSeparator: normalizeSubtitleCoupleSeparator(document.getElementById('subtitleCoupleSeparator').value),
    logSubtitle: document.getElementById('logSubtitle').value,
    profileOn: document.getElementById('profileOn').checked,
    profileMinimal: document.getElementById('profileMinimal').checked,
    profileCharOn: document.getElementById('profileCharOn').checked,
    profileUserOn: document.getElementById('profileUserOn').checked,
    profileCommonOn: document.getElementById('profileCommonOn').checked,
    profilePlacement: document.getElementById('profilePlacement').value,
    profileTextPosition: document.getElementById('profileTextPosition').value,
    profileStyle: document.getElementById('profileStyle').value,
    profileOrder: document.getElementById('profileOrder').value,
    profileExtraCount: extraProfileCount(),
    profileExtras: EXTRA_PROFILE_SLOTS.filter(slot => slot <= extraProfileCount() + 2).map(slot => {
      const prefix = extraProfilePrefix(slot);
      const read = field => document.getElementById(prefix + field).value;
      return { key:`extra${slot}`, prefix, enabled:document.getElementById(prefix + 'On').checked,
        role:read('Role'), image:normalizeProtocolRelativeUrl(read('Image')),
        imageFailed:document.getElementById(prefix + 'ImageStatus')?.dataset?.state === 'error',
        scale:read('Scale'), x:read('X'), y:read('Y'),
        name:read('Name'), desc:read('Desc'), tags:read('Tags') };
    }),
    profileImageBackgroundOn: document.getElementById('profileImageBackgroundOn').checked,
    profileCharRole: document.getElementById('profileCharRole').value,
    profileCharImage: normalizeProtocolRelativeUrl(document.getElementById('profileCharImage').value),
    profileCharImageFailed: document.getElementById('profileCharImageStatus')?.dataset?.state === 'error',
    profileCharScale: document.getElementById('profileCharScale').value,
    profileCharX: document.getElementById('profileCharX').value,
    profileCharY: document.getElementById('profileCharY').value,
    profileCharName: document.getElementById('profileCharName').value,
    profileCharDesc: document.getElementById('profileCharDesc').value,
    profileCharTags: document.getElementById('profileCharTags').value,
    profileUserRole: document.getElementById('profileUserRole').value,
    profileUserImage: normalizeProtocolRelativeUrl(document.getElementById('profileUserImage').value),
    profileUserImageFailed: document.getElementById('profileUserImageStatus')?.dataset?.state === 'error',
    profileUserScale: document.getElementById('profileUserScale').value,
    profileUserX: document.getElementById('profileUserX').value,
    profileUserY: document.getElementById('profileUserY').value,
    profileUserName: document.getElementById('profileUserName').value,
    profileUserDesc: document.getElementById('profileUserDesc').value,
    profileUserTags: document.getElementById('profileUserTags').value,
    profileRelationship: document.getElementById('profileRelationship').value,
    profileSituation: document.getElementById('profileSituation').value,
    paragraphGap: document.getElementById('paragraphGap').value,
    narrDialogueGap: document.getElementById('narrDialogueGap').value,
    softBreakSpacing: normalizeSoftBreakSpacing(document.getElementById('softBreakSpacing').value),
    outputTheme: document.getElementById('outputTheme').value,
    cardLayout: normalizeCardLayout(document.getElementById('cardLayout').value),
    spacingMode: document.getElementById('spacingMode').value,
    cardWidth: document.getElementById('cardWidth').value,
    cardBorderOn: document.getElementById('cardBorderOn').checked,
    bgColor: document.getElementById('bgColor').value,
    advancedOn,
    hrShape: advancedOn ? document.getElementById('hrShape').value : 'solid',
    hrOpacity: advancedOn ? document.getElementById('hrOpacity').value : '50',
    hrLength: advancedOn ? document.getElementById('hrLength').value : '100',
    hrVerticalSpace: advancedOn ? document.getElementById('hrVerticalSpace').value : '26',
    hr2Shape: advancedOn ? document.getElementById('hr2Shape').value : 'star',
    hr2Opacity: advancedOn ? document.getElementById('hr2Opacity').value : '50',
    hr2VerticalSpace: advancedOn ? document.getElementById('hr2VerticalSpace').value : '48',
    hr3Shape: advancedOn ? document.getElementById('hr3Shape').value : 'dots',
    hr3Opacity: advancedOn ? document.getElementById('hr3Opacity').value : '50',
    hr3VerticalSpace: advancedOn ? document.getElementById('hr3VerticalSpace').value : '36',
    gapHeight: advancedOn ? document.getElementById('gapHeight').value : '48',
    coverVerticalSpace: advancedOn ? document.getElementById('coverVerticalSpace').value : '0',
    profileOuterBackground: advancedOn && document.getElementById('profilePlacement').value === 'top'
      ? document.getElementById('profileOuterBackground').value : 'filled',
    profileItemGap: advancedOn && document.getElementById('profilePlacement').value === 'top'
      ? document.getElementById('profileItemGap').value : '0',
    profileTitleGap: advancedOn ? document.getElementById('profileTitleGap').value : '0',
    coverCardGap: advancedOn ? document.getElementById('coverCardGap').value : '0',
    cardGap: advancedOn ? document.getElementById('cardGap').value : '20',
    unifiedBottomSpace: advancedOn ? document.getElementById('unifiedBottomSpace').value : '0',
    creditWidth: advancedOn ? document.getElementById('creditWidth').value : '380',
    creditCardGap: advancedOn ? document.getElementById('creditCardGap').value : '40',
    cardInlinePadding: advancedOn ? document.getElementById('cardInlinePadding').value : '22',
    cardBodyTopSpace: advancedOn ? document.getElementById('cardBodyTopSpace').value : '0',
    cardBodyBottomSpace: advancedOn ? document.getElementById('cardBodyBottomSpace').value : '0',
    headingTopSpace: advancedOn ? document.getElementById('headingTopSpace').value : '0',
    headingBetweenSpace: advancedOn ? document.getElementById('headingBetweenSpace').value : '0',
    headingBottomSpace: advancedOn ? document.getElementById('headingBottomSpace').value : '0',
    cardTitlePadding: advancedOn ? document.getElementById('cardTitlePadding').value : '26',
    coverDividerLength: advancedOn ? document.getElementById('coverDividerLength').value : '100',
    cardDividerLength: advancedOn ? document.getElementById('cardDividerLength').value : '100',
    cardCornerRadius: advancedOn ? document.getElementById('cardCornerRadius').value : '16',
    cardTitleOrnamentOpacity: advancedOn && document.getElementById('foldTitleDecorationOn').checked
      ? document.getElementById('cardTitleOrnamentOpacity').value : '50',
    foldAutoNumberStyle: advancedOn && document.getElementById('foldTitleAutoNumber').checked
      ? document.getElementById('foldAutoNumberStyle').value : 'arabic',
    creditBorderOn: advancedOn && document.getElementById('creditBorderOn').checked,
    creditTransparentOn: advancedOn && document.getElementById('creditTransparentOn').checked,
    narrIndent: document.getElementById('narrIndent').checked,
    narrCenter: document.getElementById('narrCenter').checked,
    headingCenter: document.getElementById('headingCenter').checked,
    dialogueCenter: document.getElementById('dialogueCenter').checked,
    quoteCenter: document.getElementById('quoteCenter').checked,
    bodyFoldTitleCenter: document.getElementById('bodyFoldTitleCenter').checked,
    commentWidth: normalizeCommentWidth(document.getElementById('commentWidth').value),
    commentAlign: normalizeCommentAlign(document.getElementById('commentAlign').value),
  };
}
